name: API Gateway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: cloud-devops-learn
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Build Docker image
      run: |
        docker build -t asia-southeast2.pkg.dev/cloud-devops-learn/ecommerce-microservices-repo/api-gateway:$GITHUB_SHA .
        docker push asia-southeast2.pkg.dev/cloud-devops-learn/ecommerce-microservices-repo/api-gateway:$GITHUB_SHA

    - name: Run Unit Tests
      run:  go test ./tests/units/...

    - name: Run Integration Tests
      run:  go test ./tests/integrations/...

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy api-gateway \
          --image asia-southeast2.pkg.dev/cloud-devops-learn/ecommerce-microservices-repo/api-gateway:$GITHUB_SHA \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated
